//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSWeb.Data.DAL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DbInitializerStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DbInitializerStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSWeb.Data.DAL.DbInitializerStrings", typeof(DbInitializerStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Craterellus cornucopioides, or horn of plenty, is an edible mushroom. It is also known as the black chanterelle, black trumpet, trompette de la mort (French), trombetta dei morti (Italian) or trumpet of the dead.
        ///
        ///The Cornucopia, in Greek mythology, referred to the magnificent horn of the nymph Amalthea&apos;s goat (or of herself in goat form), that filled itself with whatever meat or drink its owner requested. It has become the symbol of plenty.
        ///
        ///Craterellus cornucopioides, or horn of plenty, is an edible m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BlackTrumpetNotes {
            get {
                return ResourceManager.GetString("BlackTrumpetNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edibles.
        /// </summary>
        internal static string CategoryNameEdibles {
            get {
                return ResourceManager.GetString("CategoryNameEdibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mushroom.
        /// </summary>
        internal static string CategoryNameMushrooms {
            get {
                return ResourceManager.GetString("CategoryNameMushrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildflowers.
        /// </summary>
        internal static string CategoryNameWildflowers {
            get {
                return ResourceManager.GetString("CategoryNameWildflowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chanterelle is the common name of fungi in the genus Cantharellus. They are among the most popularly eaten species of wild mushrooms. They are orange, yellow or white, meaty and funnel-shaped. On the lower surface, underneath the smooth cap, most species have gill-like ridges that run almost all the way down its stipe, which tapers down seamlessly from the cap. Many species emit a fruity aroma, reminiscent of apricots, and often have a mildly peppery taste (hence its German name, Pfifferling)..
        /// </summary>
        internal static string ChantrelleNotes {
            get {
                return ResourceManager.GetString("ChantrelleNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laetiporus is a genus of edible mushrooms found throughout much of the world. Some species, especially Laetiporus sulphureus, are commonly known as sulphur shelf, chicken of the woods, the chicken mushroom, or the chicken fungus because many think they taste like chicken. The name &quot;chicken of the woods&quot; is not to be confused with the edible polypore, Maitake (Grifola frondosa) known as &quot;hen of the woods&quot;, or with Lyophyllum decastes, known as the &quot;fried chicken mushroom&quot;. The name Laetiporus means &quot;with bri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChickenOfTheWoodNotes {
            get {
                return ResourceManager.GetString("ChickenOfTheWoodNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cady Hill.
        /// </summary>
        internal static string FindNameBlackTrumpet1 {
            get {
                return ResourceManager.GetString("FindNameBlackTrumpet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millstone.
        /// </summary>
        internal static string FindNameBlackTrumpet2 {
            get {
                return ResourceManager.GetString("FindNameBlackTrumpet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maple Run.
        /// </summary>
        internal static string FindNameChantrelle1 {
            get {
                return ResourceManager.GetString("FindNameChantrelle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaw Hill.
        /// </summary>
        internal static string FindNameChantrelle2 {
            get {
                return ResourceManager.GetString("FindNameChantrelle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cady&apos;s Falls Benchcut.
        /// </summary>
        internal static string FindNameChickenOfTheWood1 {
            get {
                return ResourceManager.GetString("FindNameChickenOfTheWood1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cady&apos;s Falls Climb to Leo&apos;s.
        /// </summary>
        internal static string FindNameChickenOfTheWood2 {
            get {
                return ResourceManager.GetString("FindNameChickenOfTheWood2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corner of Maple Run.
        /// </summary>
        internal static string FindNameHenOfTheWood1 {
            get {
                return ResourceManager.GetString("FindNameHenOfTheWood1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tom Gz.
        /// </summary>
        internal static string FindNameLadySlipper1 {
            get {
                return ResourceManager.GetString("FindNameLadySlipper1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darling Hill.
        /// </summary>
        internal static string FindNameLadySlipper2 {
            get {
                return ResourceManager.GetString("FindNameLadySlipper2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cady&apos;s Falls Big Rainbow.
        /// </summary>
        internal static string FindNameLeek1 {
            get {
                return ResourceManager.GetString("FindNameLeek1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cady&apos;s Fall FTFT.
        /// </summary>
        internal static string FindNameLeek2 {
            get {
                return ResourceManager.GetString("FindNameLeek2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mud City Rapids.
        /// </summary>
        internal static string FindNameTrillium1 {
            get {
                return ResourceManager.GetString("FindNameTrillium1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burlington Bike Path.
        /// </summary>
        internal static string FindNameTrillium2 {
            get {
                return ResourceManager.GetString("FindNameTrillium2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grifola frondosa is a polypore mushroom that grows in clusters at the base of trees, particularly oaks. The mushroom is commonly known among English speakers as hen of the woods, hen-of-the-woods, ram&apos;s head and sheep&apos;s head. It is typically found in late summer to early autumn. In the United States&apos; supplement market, as well as in Asian grocery stores, the mushroom is known by its Japanese name maitake (舞茸, &quot;dancing mushroom&quot;). Throughout Italian American communities in the northeastern United States, it  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HenOfTheWoodNotes {
            get {
                return ResourceManager.GetString("HenOfTheWoodNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Trumpet.
        /// </summary>
        internal static string ItemNameBlackTrumpet {
            get {
                return ResourceManager.GetString("ItemNameBlackTrumpet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chantrelle.
        /// </summary>
        internal static string ItemNameChantrelle {
            get {
                return ResourceManager.GetString("ItemNameChantrelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chicken of the wood.
        /// </summary>
        internal static string ItemNameChickenOfTheWood {
            get {
                return ResourceManager.GetString("ItemNameChickenOfTheWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hen of the wood.
        /// </summary>
        internal static string ItemNameHenOfTheWood {
            get {
                return ResourceManager.GetString("ItemNameHenOfTheWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lady Slipper.
        /// </summary>
        internal static string ItemNameLadySlipper {
            get {
                return ResourceManager.GetString("ItemNameLadySlipper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeks.
        /// </summary>
        internal static string ItemNameLeek {
            get {
                return ResourceManager.GetString("ItemNameLeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trillium.
        /// </summary>
        internal static string ItemNameTrillium {
            get {
                return ResourceManager.GetString("ItemNameTrillium", resourceCulture);
            }
        }
    }
}
